---
minimum_pre_commit_version: 2.4.0
repos:

  - repo: https://github.com/saltstack/python-tools-scripts
    rev: "0.18.4"
    hooks:
      - id: tools
        alias: actionlint
        name: Lint GitHub Actions Workflows
        files: "^.github/workflows/"
        types:
          - yaml
        args:
          - pre-commit
          - actionlint

      - id: tools
        alias: generate-workflows
        name: Generate Containers
        files: >
          (?x)^(
            tasks/containers\.py
            |
            containers\.yml
            |
            .github/workflows/\.container\.template\.j2
            |
            .*\.Dockerfile
          )$
        pass_filenames: false
        args:
          - pre-commit
          - generate-workflows

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
      - id: reorder-python-imports
        args:
          - --py38-plus
          - --add-import=from __future__ import annotations

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.8+
        args: [
          --py37-plus
        ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l 100]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/hbneat/.*\.py)$
        additional_dependencies:
          - black==22.6.0.
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, B701]
        files: ^(?!tests/).*\.py$
        exclude: src/hbneat/version.py
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security -------------------------------------------------------------------------------

  # ----- Code Analysis ------------------------------------------------------------------------->
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        exclude: ^(demo/.*|src/hbneat/version\.py|\.pre-commit-hooks/.*\.py)$
        additional_dependencies:
        - flake8-mypy-fork
        - flake8-docstrings
        - flake8-typing-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: Run mypy against the code base
        files: ^(src/|tests/).*\.py$
        args: []
        additional_dependencies:
          - types-attrs
          - types-setuptools
          - types-PyYAML
          - types-requests
          - pydantic
  # <---- Code Analysis --------------------------------------------------------------------------

  # ----- Requirements -------------------------------------------------------------------------->
  - repo: https://github.com/jazzband/pip-tools
    rev: "6.8.0"
    hooks:
      - id: pip-compile
        files: ^requirements\.(in|txt)$
        args:
          - -v
          - --output-file=requirements.txt
          - requirements.in
        additional_dependencies:
          - pip==22.0.4
  # <---- Requirements ---------------------------------------------------------------------------
