python_dependencies:
   pkg.latest:
     - pkgs:
       - gcc
       - make
       - findutils
       - binutils
       - coreutils
       - autoconf
       - autoconf-archive
       - pkg-config
       - openssl-devel
       - libffi-devel
       - bzip2-devel
       - zlib-ng-compat-devel
       - libuuid-devel
       - readline-devel
       - ncurses-devel
       - gdbm-devel
       - sqlite-devel
       - xz-devel
       - libnsl2-devel
       - expat-devel
